//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountperiod
    {
        public string ProjectID { get; set; }
        public int accountperiod1 { get; set; }
        public int Period { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int DateType { get; set; }
        public string CurrentyearPID { get; set; }
    }
}
