//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ProjectID { get; set; }
        public string AccountCode { get; set; }
        public string UpperCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> Attribute { get; set; }
        public Nullable<int> Jd { get; set; }
        public int Hsxms { get; set; }
        public string TypeCode { get; set; }
        public int Jb { get; set; }
        public Nullable<int> IsMx { get; set; }
        public Nullable<decimal> Ncye { get; set; }
        public Nullable<decimal> Qqccgz { get; set; }
        public Nullable<decimal> Jfje { get; set; }
        public Nullable<decimal> Dfje { get; set; }
        public Nullable<int> Ncsl { get; set; }
        public int Syjz { get; set; }
    }
}
