//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxiliaryFDetail
    {
        public string projectid { get; set; }
        public string Accountcode { get; set; }
        public string AuxiliaryCode { get; set; }
        public int FDetailID { get; set; }
        public int DataType { get; set; }
        public int DataYear { get; set; }
    }
}
