//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import001Datat_fzye_t
    {
        public string ProjectID { get; set; }
        public string AccountCode { get; set; }
        public int FDetailID { get; set; }
        public string ProjectCode { get; set; }
        public string Yefx { get; set; }
        public Nullable<decimal> Ncye { get; set; }
        public Nullable<double> Ncsl { get; set; }
        public int datatype { get; set; }
        public int DataYear { get; set; }
    }
}
