//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIDInformation
    {
        public string ProjectID { get; set; }
        public int ClientRiskType { get; set; }
        public string currentyearPID { get; set; }
        public string lastperiodPID { get; set; }
        public string IPOPrioryear1PID { get; set; }
        public string IPOPrioryear2PID { get; set; }
        public string IPOPrioryear3PID { get; set; }
        public int Carryforward { get; set; }
        public int FinDefine { get; set; }
        public int InvDefine { get; set; }
        public int WagDefine { get; set; }
        public int FADefine { get; set; }
    }
}
