//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class QhJzpz
    {
        public string VoucherID { get; set; }
        public string Clientid { get; set; }
        public string ProjectID { get; set; }
        public string IncNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Period { get; set; }
        public string Pzlx { get; set; }
        public string Pzh { get; set; }
        public Nullable<int> Djh { get; set; }
        public string AccountCode { get; set; }
        public string ProjectCode { get; set; }
        public string Zy { get; set; }
        public Nullable<decimal> Jfje { get; set; }
        public Nullable<decimal> Dfje { get; set; }
        public Nullable<decimal> Jfsl { get; set; }
        public Nullable<decimal> Dfsl { get; set; }
        public string ZDR { get; set; }
        public string dfkm { get; set; }
        public Nullable<decimal> Fsje { get; set; }
        public Nullable<int> Jd { get; set; }
        public Nullable<int> fllx { get; set; }
        public Nullable<int> FDetailID { get; set; }
    }
}
