//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBAdjustedSubItem
    {
        public string ProjectID { get; set; }
        public string AdjustedNO { get; set; }
        public string ID { get; set; }
        public int SortID { get; set; }
        public string FSCode { get; set; }
        public string FSName { get; set; }
        public string AccountCode { get; set; }
        public string AuxiliaryCode { get; set; }
        public string AccAuxName { get; set; }
        public int Jd { get; set; }
        public decimal Jfje { get; set; }
        public decimal Dfje { get; set; }
        public decimal Fsje { get; set; }
        public int VoucherID { get; set; }
    }
}
