//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBAdjustedItem
    {
        public string ProjectID { get; set; }
        public string AdjustedNO { get; set; }
        public string AdjustedDetails { get; set; }
        public string AdjustedType { get; set; }
        public string ReferenceList { get; set; }
        public int AdjustedyesNo { get; set; }
        public int TaxYesNo { get; set; }
        public int PSYesNo { get; set; }
        public string ResolveReference { get; set; }
        public string FAP { get; set; }
        public int IsAdjusted { get; set; }
        public string CreatorLogin { get; set; }
        public string CreatorName { get; set; }
        public System.DateTime Createdtime { get; set; }
    }
}
