//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBAux
    {
        public string ProjectID { get; set; }
        public string AccountCode { get; set; }
        public string AuxiliaryCode { get; set; }
        public string AuxiliaryName { get; set; }
        public string FSCode { get; set; }
        public string kmsx { get; set; }
        public int YEFX { get; set; }
        public string TBGrouping { get; set; }
        public decimal Sqqmye { get; set; }
        public decimal Qqccgz { get; set; }
        public decimal jfje { get; set; }
        public decimal dfje { get; set; }
        public decimal qmye { get; set; }
    }
}
