//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDetail
    {
        public string ID { get; set; }
        public string ProjectID { get; set; }
        public string FSCode { get; set; }
        public string AccountCode { get; set; }
        public string AuxiliaryCode { get; set; }
        public string AccAuxName { get; set; }
        public int DataType { get; set; }
        public string TBGrouping { get; set; }
        public int TBType { get; set; }
        public int IsAccMx { get; set; }
        public int IsMx { get; set; }
        public int IsAux { get; set; }
        public string kmsx { get; set; }
        public int Yefx { get; set; }
        public string SourceFSCode { get; set; }
        public decimal Sqqmye { get; set; }
        public decimal Qqccgz { get; set; }
        public decimal jfje { get; set; }
        public decimal dfje { get; set; }
        public decimal CrjeJF { get; set; }
        public decimal CrjeDF { get; set; }
        public decimal AjeJF { get; set; }
        public decimal AjeDF { get; set; }
        public decimal RjeJF { get; set; }
        public decimal RjeDF { get; set; }
        public decimal TaxBase { get; set; }
        public decimal PY1 { get; set; }
        public decimal jfje1 { get; set; }
        public decimal dfje1 { get; set; }
        public decimal jfje2 { get; set; }
        public decimal dfje2 { get; set; }
    }
}
