//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDetailExtra
    {
        public string ID { get; set; }
        public string ProjectID { get; set; }
        public string ReferenceList { get; set; }
        public int SelectedSampleLebelYesNo { get; set; }
        public int MaterialityProgram { get; set; }
        public int SelectSampleMethod { get; set; }
        public int DrSelectedSampleLebelYesNo { get; set; }
        public int DrMaterialityProgram { get; set; }
        public int DrSelectSampleMethod { get; set; }
        public int CrSelectedSampleLebelYesNo { get; set; }
        public int CrMaterialityProgram { get; set; }
        public int CrSelectSampleMethod { get; set; }
        public int SampleSelectedYesNo { get; set; }
        public int SampleSelectedType { get; set; }
        public decimal ConsultBalance { get; set; }
        public decimal ConfirmBalance { get; set; }
        public string ConsultType { get; set; }
        public string RelatedClientID { get; set; }
        public int SampleSelecteStep { get; set; }
        public int ErrorYesNO { get; set; }
        public int StepofSample { get; set; }
        public string AdjustedNo { get; set; }
        public string AccountProperty { get; set; }
        public string Memo { get; set; }
    }
}
