//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBVoucher
    {
        public string VoucherID { get; set; }
        public string Clientid { get; set; }
        public string ProjectID { get; set; }
        public string IncNo { get; set; }
        public System.DateTime Date { get; set; }
        public int Period { get; set; }
        public string Pzlx { get; set; }
        public string Pzh { get; set; }
        public int Djh { get; set; }
        public string AccountCode { get; set; }
        public string ProjectCode { get; set; }
        public string Zy { get; set; }
        public decimal Jfje { get; set; }
        public decimal Dfje { get; set; }
        public decimal Jfsl { get; set; }
        public decimal Dfsl { get; set; }
        public string ZDR { get; set; }
        public string dfkm { get; set; }
        public int Jd { get; set; }
        public decimal Fsje { get; set; }
        public string Wbdm { get; set; }
        public Nullable<decimal> Wbje { get; set; }
        public decimal Hl { get; set; }
        public int FLLX { get; set; }
        public int SampleSelectedYesNo { get; set; }
        public int SampleSelectedType { get; set; }
        public string TBGrouping { get; set; }
        public string EASREF { get; set; }
        public int AccountingAge { get; set; }
        public int qmyegc { get; set; }
        public int Stepofsample { get; set; }
        public int ErrorYesNo { get; set; }
        public Nullable<int> FDetailID { get; set; }
    }
}
