//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJY2EAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbwlzl
    {
        public string ID { get; set; }
        public string ProjectID { get; set; }
        public string fsCode { get; set; }
        public string AccountCode { get; set; }
        public string AuxiliaryCode { get; set; }
        public int AgeAnalysis { get; set; }
        public decimal ZLD1 { get; set; }
        public decimal ZLD2 { get; set; }
        public decimal ZLD3 { get; set; }
        public decimal ZLD4 { get; set; }
        public decimal ZLD5 { get; set; }
        public decimal ZLD6 { get; set; }
        public decimal ZLD7 { get; set; }
        public decimal ZLD8 { get; set; }
        public decimal ZLD9 { get; set; }
        public int significant { get; set; }
        public int Impairmenttestmethod { get; set; }
        public decimal impairmentamount { get; set; }
        public int BalanceAnalysis { get; set; }
        public string memo { get; set; }
        public decimal HZZBZLD1 { get; set; }
        public decimal HZZBZLD2 { get; set; }
        public decimal HZZBZLD3 { get; set; }
        public decimal HZZBZLD4 { get; set; }
        public decimal HZZBZLD5 { get; set; }
        public decimal HZZBZLD6 { get; set; }
        public decimal HZZBZLD7 { get; set; }
        public decimal HZZBZLD8 { get; set; }
        public decimal HZZBZLD9 { get; set; }
        public int Creditperiod { get; set; }
    }
}
